export enum UserRole {
  ADMIN = 'ADMIN',
  EXECUTIVE = 'EXECUTIVE',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  PROCUREMENT_MANAGER = 'PROCUREMENT_MANAGER',
  HR_MANAGER = 'HR_MANAGER',
  SITE_ENGINEER = 'SITE_ENGINEER',
  WAREHOUSE_MANAGER = 'WAREHOUSE_MANAGER',
  EMPLOYEE = 'EMPLOYEE'
}

export enum ProjectStatus {
  PLANNING = 'PLANNING',
  ACTIVE = 'ACTIVE',
  ON_HOLD = 'ON_HOLD',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED'
}

export enum ActivityStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ESCALATED = 'ESCALATED'
}

export enum Currency {
  AED = 'AED',
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP'
}
